//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_assignment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Assignment_dbEntities1 : DbContext
    {
        public Assignment_dbEntities1()
            : base("name=Assignment_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Brunch> tb_Brunch { get; set; }
        public virtual DbSet<tb_Rating> tb_Rating { get; set; }
        public virtual DbSet<tb_User> tb_User { get; set; }
    }
}
