//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Brunch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Brunch()
        {
            this.tb_Rating = new HashSet<tb_Rating>();
        }
    
        public int BrunchId { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public int CostForTwo { get; set; }
        public string Hours { get; set; }
        public int AverRating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Rating> tb_Rating { get; set; }
    }
}
