//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Rating
    {
        public int RatingId { get; set; }
        public int BrunchId { get; set; }
        public int UserId { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
        public System.DateTime RatingDate { get; set; }
    
        public virtual tb_Brunch tb_Brunch { get; set; }
        public virtual tb_User tb_User { get; set; }
    }
}
