
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (1, 'Gerard', '431 Almo Pass', 'Citeguh', 195, '9:38 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (2, 'Jack', '68106 Hagan Hill', 'Sipirok', 258, '3:19 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (3, 'Etienne', '7010 Oneill Place', 'Girardot', 133, '6:34 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (4, 'Marleah', '5 Dahle Court', 'Kodyma', 83, '10:40 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (5, 'Nanine', '04 Express Alley', 'Yishi', 116, '11:32 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (6, 'Khalil', '30132 Manufacturers Center', 'Longquan', 97, '10:48 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (7, 'Lalo', '504 Mccormick Drive', 'Montalvão', 229, '4:36 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (8, 'Ianthe', '07674 Roth Junction', 'El Caño', 127, '10:17 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (9, 'Georgianne', '29271 Londonderry Point', 'Samoš', 110, '5:22 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (10, 'Selina', '29273 Elka Point', 'Suqu', 83, '9:08 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (11, 'Annemarie', '3 Holmberg Point', 'Zushi', 16, '10:34 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (12, 'Clarice', '531 Quincy Alley', 'Ruzhany', 80, '10:12 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (13, 'Aloysia', '26 Arkansas Point', 'Marietta', 163, '1:07 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (14, 'Blinny', '8 Southridge Park', 'Capira', 292, '8:47 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (15, 'Kyla', '7896 Sage Court', 'Sherwood Park', 161, '4:14 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (16, 'Vachel', '795 Marcy Trail', 'Kalawit', 149, '3:42 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (17, 'Blancha', '7090 Swallow Road', 'Paty do Alferes', 266, '5:48 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (18, 'Brendis', '43 Kings Junction', 'Lampari', 102, '8:39 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (19, 'Puff', '1 Surrey Street', 'Sanyang', 155, '5:19 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (20, 'Maude', '4 Dottie Center', 'Xiwanzi', 186, '1:17 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (21, 'Regan', '83 Rieder Alley', 'Riangbao', 65, '12:52 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (22, 'Ragnar', '7676 Ridge Oak Crossing', 'Touzao', 114, '5:33 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (23, 'Hannis', '432 Dixon Terrace', 'Smętowo Graniczne', 169, '10:00 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (24, 'Annis', '950 Orin Way', 'Bhāndāria', 252, '11:59 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (25, 'Zeb', '357 Oriole Hill', 'Namur', 167, '3:25 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (26, 'Rozamond', '68 Pankratz Hill', 'San Jose', 82, '3:56 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (27, 'Jourdan', '277 Warbler Avenue', 'Lujiao', 71, '10:05 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (28, 'Pebrook', '6 Schurz Avenue', 'Shcherbinka', 59, '5:24 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (29, 'Baldwin', '15184 Clemons Avenue', 'San Javier', 36, '11:04 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (30, 'Jarred', '44 Magdeline Circle', 'Constantia', 24, '7:31 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (31, 'Micaela', '610 School Lane', 'Tulihe', 136, '11:16 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (32, 'Sean', '6677 Farwell Circle', 'Gelap', 223, '2:02 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (33, 'Evvy', '66 Thackeray Way', 'Ganjiang', 86, '8:23 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (34, 'Magdalena', '5 Mayer Crossing', 'Quwa', 135, '7:44 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (35, 'Marnie', '2189 Meadow Ridge Place', 'Wuqiao', 267, '6:23 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (36, 'Saunderson', '838 Barnett Court', 'Aioi', 119, '11:03 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (37, 'Karlis', '15759 Towne Terrace', 'Limón', 185, '10:47 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (38, 'Shell', '0 Talmadge Drive', 'Além do Rio', 64, '2:01 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (39, 'Michele', '2315 Hudson Lane', 'Tsaritsyno', 154, '11:12 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (40, 'Beatrisa', '397 Amoth Park', 'Gyōda', 152, '2:30 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (41, 'Pedro', '83 Miller Street', 'Baku', 239, '12:01 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (42, 'Marcelline', '762 Erie Trail', 'Sankt Lorenzen im Mürztal', 240, '8:59 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (43, 'Del', '5388 Lien Point', 'Malaryta', 182, '12:29 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (44, 'Miriam', '72 Graedel Court', 'Alegre', 252, '5:21 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (45, 'Martie', '68 Elmside Lane', 'Mpulungu', 298, '3:33 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (46, 'Alie', '71829 Macpherson Circle', 'Kotabaru', 221, '5:01 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (47, 'Diahann', '5 Caliangt Circle', 'Ménaka', 74, '7:44 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (48, 'Wade', '39 Eggendart Place', 'Velykyy Klyuchiv', 157, '10:18 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (49, 'Theodor', '19221 Reinke Court', 'Maliang', 233, '8:12 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (50, 'Mag', '44406 Russell Drive', 'Vlycháda', 240, '9:59 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (51, 'Bianca', '1 Donald Plaza', 'Pinhal General', 26, '6:44 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (52, 'Wilton', '33877 Scoville Crossing', 'Al Khushnīyah', 279, '4:26 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (53, 'Michale', '59617 Vidon Hill', 'Kuncen', 16, '2:43 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (54, 'Gustavo', '18533 2nd Avenue', 'Strasbourg', 39, '3:49 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (55, 'Elwira', '373 Birchwood Pass', 'Offenbach', 202, '5:29 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (56, 'Katie', '38568 Novick Junction', 'Zaporizhzhya', 96, '7:17 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (57, 'Malissa', '5488 Buena Vista Pass', 'Tiniguiban', 121, '8:14 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (58, 'Adler', '1479 Lake View Point', 'Utara', 34, '5:35 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (59, 'Caril', '8 Di Loreto Junction', 'Chatuchak', 192, '8:40 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (60, 'Monique', '5 Maryland Lane', 'Волочаевское', 249, '5:14 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (61, 'Gregg', '90681 Manufacturers Circle', 'Xinglong', 86, '8:05 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (62, 'Karel', '2291 Prairie Rose Way', 'Skomielna Czarna', 3, '3:18 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (63, 'Cad', '8623 Vernon Way', 'Los Lotes', 295, '8:13 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (64, 'Phineas', '86404 Commercial Alley', 'Jiaoshanhe', 115, '2:28 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (65, 'Fernanda', '9 Bluejay Lane', 'Stockholm', 36, '10:31 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (66, 'Sylvia', '815 Jenna Plaza', 'Flandes', 283, '12:11 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (67, 'Cody', '2810 Monica Crossing', 'Épinal', 173, '6:42 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (68, 'Benedikt', '7071 Golden Leaf Crossing', 'Bununu Dass', 168, '10:28 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (69, 'Noel', '40850 Bashford Trail', 'Baiju', 138, '5:32 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (70, 'Katrinka', '842 4th Pass', 'Tivat', 68, '4:28 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (71, 'Retha', '228 Delaware Junction', 'Vinhais', 267, '10:41 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (72, 'Nicholle', '9409 Del Mar Alley', 'Basoko', 102, '6:36 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (73, 'Fredric', '49918 Pierstorff Court', 'Yixing', 6, '2:22 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (74, 'Anne-marie', '77082 Meadow Ridge Point', 'Arosbaya', 245, '10:27 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (75, 'Thaxter', '74551 Fremont Center', 'Barajevo', 294, '8:26 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (76, 'Meara', '8 Browning Street', 'Zárate', 59, '10:17 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (77, 'Maxim', '50152 8th Crossing', 'Tiebiancheng', 30, '11:25 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (78, 'Zia', '1 Oak Valley Drive', 'Vallenar', 216, '3:21 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (79, 'Agace', '6698 Pankratz Lane', 'El Carmen', 273, '3:38 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (80, 'Diannne', '6455 Everett Way', 'Obas', 275, '4:37 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (81, 'Nolan', '1 Green Ridge Street', 'Cikadu', 247, '11:15 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (82, 'Cleavland', '4164 Blue Bill Park Point', 'Poříčí nad Sázavou', 18, '7:31 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (83, 'Timofei', '902 Hanson Park', 'Makungu', 199, '11:37 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (84, 'Marc', '38 Caliangt Point', 'Ina', 240, '9:51 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (85, 'Celia', '22277 Farragut Parkway', 'Kadusirung Hilir', 175, '9:33 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (86, 'Theodor', '51243 Morningstar Junction', 'Bombarral', 148, '8:39 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (87, 'Dee', '7 Corry Avenue', 'Nanae', 211, '5:13 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (88, 'Jenny', '775 Bonner Terrace', 'Krajan Siki', 168, '10:30 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (89, 'Maryjo', '18 Morning Avenue', 'Pomahuaca', 238, '12:49 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (90, 'Kania', '8459 Steensland Street', 'Nîmes', 228, '4:02 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (91, 'Jeana', '5450 Manitowish Alley', 'Paoay', 126, '10:06 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (92, 'Dottie', '3 Sachtjen Road', 'Monamon', 45, '3:51 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (93, 'Bruis', '522 Logan Circle', 'Nahrīn', 123, '10:30 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (94, 'Brodie', '44 Farmco Place', 'Khlong Yai', 51, '4:50 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (95, 'Isidora', '2880 Debs Circle', 'Gatak', 208, '7:35 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (96, 'Brodie', '33100 Melvin Hill', 'Kinel’-Cherkassy', 237, '8:28 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (97, 'Romain', '37 Bunting Alley', 'Njurunda', 119, '10:25 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (98, 'Shell', '5 Derek Crossing', 'Pag-asa', 128, '10:55 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (99, 'Sherrie', '771 Little Fleur Point', 'Morelos', 284, '12:29 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (100, 'Kermit', '281 4th Alley', 'Nouakchott', 150, '7:53 PM', 1);