
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (1, 'Friedrich', '96377 Holmberg Pass', 'Maliang', '$206.78', '3:26 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (2, 'Charlot', '71 Little Fleur Point', 'Paris 12', '$42.35', '3:33 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (3, 'Heda', '08 Oak Valley Hill', 'Caxambu', '$272.61', '1:20 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (4, 'Arline', '29922 Moland Drive', 'Vantaa', '$207.96', '4:39 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (5, 'Ferd', '9811 Elmside Circle', 'Austin', '$69.13', '1:40 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (6, 'Selene', '79 School Center', 'Saint-Paul', '$299.32', '1:08 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (7, 'Norby', '8 Little Fleur Pass', 'Caringin', '$197.93', '9:16 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (8, 'Buddie', '1 Lakeland Center', 'Cawayan Bugtong', '$172.98', '10:20 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (9, 'Kial', '73 Anniversary Junction', 'Épinal', '$127.82', '6:20 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (10, 'Brendon', '92 Green Ridge Circle', 'Tsyelyakhany', '$151.21', '4:58 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (11, 'Edvard', '9527 Cody Point', 'Sukaharja', '$41.15', '2:52 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (12, 'Gabriell', '90 Eastlawn Alley', 'Qili', '$262.54', '2:56 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (13, 'Jacinta', '3590 Leroy Circle', 'Kuantan', '$152.37', '6:01 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (14, 'Aldis', '767 Sutteridge Avenue', 'Nombre de Jesús', '$201.68', '7:19 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (15, 'Aleece', '06862 Warrior Point', 'Kajok', '$24.65', '5:26 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (16, 'Niki', '304 Rusk Drive', 'Vitarte', '$55.62', '3:21 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (17, 'Mohandas', '7136 Jackson Terrace', 'Jabon', '$108.44', '11:39 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (18, 'Dominica', '66 Calypso Park', 'Villejuif', '$27.81', '3:12 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (19, 'Anderson', '4 Express Terrace', 'Avignon', '$123.69', '9:23 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (20, 'Rossy', '89125 Hintze Terrace', 'Old Shinyanga', '$111.48', '11:44 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (21, 'Sinclare', '0 Pennsylvania Crossing', 'Paranaguá', '$64.84', '12:48 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (22, 'Feliks', '572 Mockingbird Alley', 'Derbur', '$255.80', '12:55 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (23, 'Tan', '2341 Spaight Hill', 'Shantoudian', '$177.04', '7:12 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (24, 'Freddie', '37 Pawling Park', 'Shuangmiaojie', '$172.56', '4:46 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (25, 'Bradford', '33415 Helena Circle', 'Al Mazra‘ah ash Sharqīyah', '$174.75', '1:11 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (26, 'Ronald', '4748 Messerschmidt Point', 'Newcastle', '$75.84', '9:54 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (27, 'Martainn', '05723 Clove Plaza', 'Serra Talhada', '$27.53', '12:19 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (28, 'Whitby', '0 Melody Trail', 'Shatki', '$47.95', '5:39 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (29, 'Clair', '5606 Ridge Oak Drive', 'Carig', '$45.75', '1:35 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (30, 'Ralph', '41 Golf View Road', 'Gia Ray', '$83.59', '2:37 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (31, 'Gare', '66 Vera Park', 'Mloko', '$191.19', '6:46 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (32, 'Nicole', '59 Oriole Point', 'Rizal', '$294.37', '2:09 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (33, 'Ivan', '98965 Ramsey Alley', 'Levin', '$278.45', '2:04 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (34, 'Brittan', '02 Fairfield Circle', 'Ashiya', '$9.68', '3:39 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (35, 'Jeralee', '4 Eastlawn Circle', 'Xinjiezi', '$270.17', '3:33 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (36, 'Nicholas', '82 Cherokee Park', 'Canaman', '$208.15', '6:17 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (37, 'Yorker', '96673 Lien Terrace', 'São Sebastião do Caí', '$291.99', '6:20 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (38, 'De witt', '1 Shoshone Hill', 'Pithári', '$172.13', '7:52 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (39, 'Loleta', '2554 Sutteridge Junction', 'Baisha', '$174.34', '9:29 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (40, 'Athene', '45 Hovde Avenue', 'Loandjili', '$161.80', '9:24 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (41, 'Corrie', '59 Anderson Terrace', 'Menol', '$241.78', '12:23 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (42, 'Kenon', '2107 Caliangt Circle', 'Bouças', '$41.43', '8:04 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (43, 'Duke', '625 Sachtjen Point', 'Komorní Lhotka', '$55.03', '7:30 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (44, 'Derick', '39 Lotheville Pass', 'Khānewāl', '$184.62', '11:35 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (45, 'Amy', '6 Cambridge Terrace', 'Divača', '$289.20', '3:10 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (46, 'Marlon', '39726 Schurz Junction', 'Ōdate', '$8.29', '3:52 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (47, 'Brant', '7067 Oak Valley Center', 'Smiltene', '$238.47', '3:53 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (48, 'Bettine', '85110 Myrtle Center', 'Maco', '$31.75', '7:50 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (49, 'Noam', '61677 Del Sol Terrace', 'Kamloops', '$234.20', '4:28 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (50, 'Wrennie', '3717 Gale Plaza', 'Luoshan', '$170.36', '5:14 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (51, 'Aristotle', '37255 Dexter Junction', 'Ngudu', '$62.70', '1:34 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (52, 'Johnette', '45922 Lien Parkway', 'La Unión', '$208.97', '6:41 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (53, 'Rosaline', '628 Rutledge Way', 'Independencia', '$21.86', '4:03 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (54, 'Barron', '275 Lake View Lane', 'Mungo', '$10.96', '8:09 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (55, 'Alfi', '1595 Moose Trail', 'Tsukuba', '$108.42', '2:27 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (56, 'Suellen', '7331 Namekagon Plaza', 'Jesús María', '$96.77', '11:56 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (57, 'Jess', '05349 Hauk Hill', 'Baiyanghe', '$167.85', '11:17 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (58, 'Tirrell', '0 Schurz Park', 'Tanjung Kidul', '$144.58', '10:58 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (59, 'Candra', '86 Forest Alley', 'Poitiers', '$156.22', '3:24 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (60, 'Katey', '286 Cambridge Trail', 'Höllviken', '$20.94', '3:57 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (61, 'Bobbe', '5 Schiller Avenue', 'Rapas', '$69.94', '4:35 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (62, 'Ofilia', '47 Southridge Parkway', 'Situ', '$191.86', '8:29 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (63, 'Lennie', '378 Hooker Place', 'Vistino', '$112.19', '11:30 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (64, 'Ezra', '4289 Nevada Point', 'Sanshui', '$235.21', '5:04 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (65, 'Justina', '7151 Raven Drive', 'Bor Ondor', '$51.31', '2:13 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (66, 'Trueman', '22 Express Court', 'Tlatah', '$62.86', '6:00 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (67, 'Ave', '3015 Delaware Alley', 'Dengteke', '$191.91', '10:24 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (68, 'Philippa', '5899 Canary Street', 'Turkestan', '$77.27', '12:29 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (69, 'Lock', '3691 Mosinee Circle', 'Sigeng', '$179.26', '10:04 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (70, 'Gisela', '3271 Lyons Hill', 'Shazi', '$13.01', '5:46 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (71, 'Rafael', '90 Talisman Street', 'Thị Trấn Phú Mỹ', '$7.73', '1:21 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (72, 'Melosa', '857 4th Junction', 'Sindangpanji', '$15.60', '2:34 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (73, 'Gabey', '31467 Montana Center', 'Gongbuxue', '$6.81', '2:40 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (74, 'Kincaid', '230 Victoria Hill', 'Lewoeleng', '$72.31', '11:53 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (75, 'Minta', '7889 Scott Lane', 'Levashi', '$67.70', '6:58 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (76, 'Clark', '24 Coleman Place', 'Tinambac', '$87.89', '5:47 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (77, 'Ado', '838 Fairview Avenue', 'Lubāna', '$47.21', '11:07 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (78, 'Wynn', '4043 Calypso Terrace', 'Alkmaar', '$166.66', '4:34 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (79, 'Oona', '8 Bluejay Plaza', 'Independencia', '$227.38', '11:37 AM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (80, 'Ly', '502 Sycamore Junction', 'New Panamao', '$151.54', '8:52 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (81, 'Angela', '96622 Bayside Trail', 'Lanos', '$161.45', '12:59 AM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (82, 'Ainslie', '863 Northland Plaza', 'Ticllos', '$127.28', '8:01 PM', 4);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (83, 'Aurilia', '9 Hayes Road', 'Babana', '$118.11', '2:27 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (84, 'Gilbertine', '0 Fremont Pass', 'Paranapanema', '$195.96', '3:28 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (85, 'Viole', '45817 Jenifer Plaza', 'Chenqiao', '$114.84', '4:00 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (86, 'Nanete', '6662 Elmside Hill', 'Sarreguemines', '$46.72', '7:46 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (87, 'Francene', '21245 Superior Junction', 'Gedongmulyo', '$173.48', '11:42 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (88, 'Simonette', '5603 Blaine Road', 'Skärhamn', '$116.52', '10:57 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (89, 'Barbie', '2 Nancy Way', 'Kinloch', '$135.82', '12:55 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (90, 'Ado', '9762 Oriole Road', 'Pagatan', '$47.30', '5:10 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (91, 'Nadiya', '6 Mallory Alley', 'Dagui', '$63.03', '8:59 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (92, 'Zechariah', '50 Carpenter Hill', 'Tumba', '$251.60', '4:54 AM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (93, 'Deane', '522 Bayside Lane', 'Padangulaktanding', '$204.83', '12:51 PM', 3);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (94, 'Pier', '4 Hagan Street', 'Fangfan', '$103.17', '1:05 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (95, 'Amil', '4 Pepper Wood Circle', 'Sukamanah', '$16.23', '12:56 AM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (96, 'Niki', '20 Cascade Junction', 'Da’anshan', '$119.08', '8:22 PM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (97, 'Menard', '7467 Johnson Alley', 'Diourbel', '$128.24', '1:49 PM', 5);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (98, 'Shela', '5 Pankratz Pass', 'Tianzishan', '$213.92', '10:48 PM', 1);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (99, 'Erica', '651 East Center', 'Sungai Raya', '$162.79', '4:35 AM', 2);
insert into tb_Brunch (BrunchId, Name, Street, Suburb, CostForTwo, Hours, AverRating) values (100, 'Karrie', '0 Northview Junction', 'Filipstad', '$41.12', '10:05 AM', 5);